
package com.sltc.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidInputValues", targetNamespace = "http://BankService.services.ramesh/")
public class InvalidInputValues_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidInputValues faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidInputValues_Exception(String message, InvalidInputValues faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidInputValues_Exception(String message, InvalidInputValues faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sltc.client.InvalidInputValues
     */
    public InvalidInputValues getFaultInfo() {
        return faultInfo;
    }

}
